"""Per-request context as pure ASGI middleware (safe for SSE responses later).

- request_id: always generated by the server; a client X-Request-Id never overrides it.
- channel: from X-Edge-Channel, which shop Nginx overwrites to "shop" and only the
  Streamlit server sets to "ops" on the internal network (D-17). Anything else is None.
- body limit: rejects bodies over MAX_BODY_BYTES even when Content-Length is absent.
"""

from __future__ import annotations

import json
import time
import uuid
from typing import Literal

from starlette.types import ASGIApp, Message, Receive, Scope, Send

Channel = Literal["shop", "ops"]
VALID_CHANNELS: frozenset[str] = frozenset({"shop", "ops"})


class RequestContextMiddleware:
    def __init__(self, app: ASGIApp, max_body_bytes: int) -> None:
        self.app = app
        self.max_body_bytes = max_body_bytes

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if scope["type"] != "http":
            await self.app(scope, receive, send)
            return

        request_id = str(uuid.uuid4())
        headers = {k.decode("latin-1").lower(): v.decode("latin-1") for k, v in scope["headers"]}
        channel = headers.get("x-edge-channel")
        state = scope.setdefault("state", {})
        state["request_id"] = request_id
        state["channel"] = channel if channel in VALID_CHANNELS else None
        state["started"] = time.perf_counter()

        async def send_with_id(message: Message) -> None:
            if message["type"] == "http.response.start":
                raw = list(message.get("headers", []))
                raw.append((b"x-request-id", request_id.encode()))
                raw.append((b"cache-control", b"no-store"))
                message["headers"] = raw
            await send(message)

        declared = headers.get("content-length")
        if declared is not None and (not declared.isdigit() or int(declared) > self.max_body_bytes):
            await _reject_too_large(request_id, send_with_id)
            return

        # Bodies are small (≤256 KiB), so buffer once, enforce the limit, then replay.
        chunks: list[bytes] = []
        received = 0
        more_body = True
        while more_body:
            message = await receive()
            if message["type"] != "http.request":
                break
            chunk = message.get("body", b"")
            received += len(chunk)
            if received > self.max_body_bytes:
                await _reject_too_large(request_id, send_with_id)
                return
            chunks.append(chunk)
            more_body = message.get("more_body", False)
        body = b"".join(chunks)
        replayed = False

        async def replay_receive() -> Message:
            nonlocal replayed
            if not replayed:
                replayed = True
                return {"type": "http.request", "body": body, "more_body": False}
            return await receive()

        await self.app(scope, replay_receive, send_with_id)


async def _reject_too_large(request_id: str, send: Send) -> None:
    body = json.dumps(
        {"request_id": request_id, "error": {"code": "BODY_TOO_LARGE", "message": "요청 크기가 너무 큽니다."}},
        ensure_ascii=False,
    ).encode()
    await send(
        {
            "type": "http.response.start",
            "status": 413,
            "headers": [(b"content-type", b"application/json"), (b"content-length", str(len(body)).encode())],
        }
    )
    await send({"type": "http.response.body", "body": body})
